extensions:
  health_check:

receivers:
  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268

processors:
#  span:
#    include:
#      match_type:  attributes
#      attributes:
#        - key: "method"
#    name:
#      from_attributes: ["method"]
  batch:


exporters:
  logging:
    logLevel: debug
  file:
    path: ./filename.json
  mongo:
    url: "mongodb://8.130.164.80:27017"
    tag: "method"

service:

  pipelines:

    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [mongo]

    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check]
